### ISSUE TITLE
Nan loss on ImageNet_R dataset

### ISSUE THREAD

**Issue by SuQinghang** [DoubleClass/GMM#16]
Hello, thanks for sharing the great work! 
I meet some questions when conducting experiments on ImageNet_R dataset.
1. I encountered an issue with NaN Loss while reproducing the experiments on the ImageNet-R dataset, and I have attached my configuration file below. Do you have any specific suggestions for addressing this problem? 
2. Additionally, could you please share the data splits and configuration files for the other two datasets as well?

minigpt4_stage2_finetune.yaml
```yaml
model:
  arch: mini_gpt4
  model_type: pretrain_vicuna0

  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '.../minigpt4/models/prerained_minigpt4_7b.pth'

datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-7
  min_lr: 1e-6
  warmup_lr: 1e-7

  weight_decay: 0.05
  max_epoch: 2
  iters_per_epoch: 200
  batch_size_train: 2
  batch_size_eval: 12
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "output/"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

task_num: 10
```
